// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-central-1',
  aws_cognito_identity_pool_id: 'eu-central-1:70cd1913-15ae-4c7e-967c-5107f657e3a1',
  aws_cognito_region: 'eu-central-1',
  aws_user_pools_id: 'eu-central-1_dX7eHpq3r',
  aws_user_pools_web_client_id: '2mlspn31cdkl7js1uf3t0lef3h',
  oauth: {},
  aws_appsync_graphqlEndpoint: 'https://gkosvyyfmfhvnfw6ad6rrpkzta.appsync-api.eu-central-1.amazonaws.com/graphql',
  aws_appsync_region: 'eu-central-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_content_delivery_bucket: 'quasar-print-20200327111617-hostingbucket-dev',
  aws_content_delivery_bucket_region: 'eu-central-1',
  aws_content_delivery_url: 'https://d1qgx38fpn45jx.cloudfront.net'
}

export default awsmobile
